//! Bash-specific rendering and persistent integration for `ghis`.
//!
//! The generated file is deliberately Bash source. It is inert for noninteractive
//! Bash processes, so scripts and `bash -c` do not inherit command wrappers.

use clap::Command;
use clap_complete::{Shell, generate};
use std::ffi::{OsStr, OsString};
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use crate::managed_file::{self, ManagedBlock};

pub use super::zsh::{IntegrationHealth, SetupReport};
use super::{ShellKind, ShellRenderer, ShellSpec, private};

pub(super) struct BashRenderer;

impl private::Sealed for BashRenderer {}

impl ShellRenderer for BashRenderer {
    fn spec(&self) -> ShellSpec {
        ShellKind::Bash.spec()
    }

    fn render_init(&self, binary: &str) -> String {
        bash_init_script(binary)
    }

    fn render_completion(&self, command: &mut Command, binary: &str) -> Vec<u8> {
        let mut output = Vec::new();
        generate(Shell::Bash, command, binary, &mut output);
        output
    }

    fn startup_file(&self, home: &Path) -> PathBuf {
        bashrc_path(home)
    }

    fn install(
        &self,
        startup_file: &Path,
        init_file: &Path,
        init_script: &str,
    ) -> io::Result<SetupReport> {
        setup_rendered(startup_file, init_file, init_script)
    }

    fn uninstall(&self, startup_file: &Path) -> io::Result<bool> {
        uninstall(startup_file)
    }

    fn integration_is_loaded(&self) -> bool {
        integration_is_loaded()
    }

    fn integration_health(&self) -> IntegrationHealth {
        integration_health()
    }

    fn healthy_marker(&self) -> &'static str {
        HEALTHY_MARKER
    }

    fn inherited_health_marker(&self) -> Option<OsString> {
        std::env::var_os(HEALTH_ENV)
    }

    fn integration_is_installed(
        &self,
        startup_file: &Path,
        init_file: &Path,
        binary: &str,
    ) -> bool {
        integration_is_installed(startup_file, init_file, binary)
    }

    fn setup_command(&self) -> &'static str {
        "ghis shell setup bash"
    }
}

pub(super) static RENDERER: BashRenderer = BashRenderer;

/// Start marker for the block owned by ghis in `.bashrc`.
pub const START_MARKER: &str = "# >>> ghis setup >>>";
/// End marker for the block owned by ghis in `.bashrc`.
pub const END_MARKER: &str = "# <<< ghis setup <<<";
/// Set only after the interactive Bash wrapper has loaded.
pub const LOADED_ENV: &str = "GHIS_SHELL_INTEGRATION";
/// Versioned health marker emitted after all Bash functions are defined.
pub const HEALTH_ENV: &str = "GHIS_SHELL_INTEGRATION_HEALTH";
/// Health marker emitted by the current Bash integration.
pub const HEALTHY_MARKER: &str = "bash-v1";

/// Bash always reads `.bashrc` from the user's home directory for interactive
/// non-login shells. We intentionally do not follow `BASH_ENV`, which applies
/// to noninteractive Bash and must remain untouched.
pub fn bashrc_path(home: &Path) -> PathBuf {
    home.join(".bashrc")
}

/// Quote a value as one POSIX shell word.
///
/// The generated wrapper embeds only a binary path or startup-file path. Single
/// quotes prevent expansion, command substitution, globbing, and word splitting;
/// the sole escaped character is a literal single quote.
pub fn shell_quote(value: &str) -> String {
    if value.is_empty() {
        return "''".to_owned();
    }

    let mut quoted = String::with_capacity(value.len() + 2);
    quoted.push('\'');
    for character in value.chars() {
        if character == '\'' {
            quoted.push_str("'\\''");
        } else {
            quoted.push(character);
        }
    }
    quoted.push('\'');
    quoted
}

/// Render the interactive Bash wrapper.
///
/// All user arguments stay in `"$@"`; the wrapper never evaluates command
/// arguments or output. `GHIS_WRAPPER_ACTIVE` is scoped to the child command so
/// recursive invocations return to the underlying executable.
pub fn bash_init_script(binary: &str) -> String {
    let binary = shell_quote(binary);
    format!(
        r#"# Generated by ghis. Do not edit this file; rerun `ghis shell setup bash`.
# Noninteractive Bash must remain pristine: do not install functions or prompt
# hooks for scripts, `bash -c`, or BASH_ENV consumers.
case $- in
  *i*) ;;
  *) return 0 ;;
esac

export GHIS_SHELL_INTEGRATION=1
unset GHIS_SHELL_INTEGRATION_HEALTH

ghis_dispatch() {{
  local ghis_kind=$1
  shift
  if [[ ${{GHIS_BYPASS:-0}} == 1 || ${{GHIS_WRAPPER_ACTIVE:-0}} == 1 ]]; then
    command "$ghis_kind" "$@"
    return $?
  fi
  if ! command -v {binary} >/dev/null 2>&1; then
    command "$ghis_kind" "$@"
    return $?
  fi
  GHIS_WRAPPER_ACTIVE=1 command {binary} "$ghis_kind" -- "$@"
}}

ghis_git_read_only() {{
  local ghis_arg
  local ghis_option_arg=0
  for ghis_arg in "$@"; do
    if (( ghis_option_arg )); then
      ghis_option_arg=0
      continue
    fi
    case $ghis_arg in
      -C|-c|--config|--exec-path|--git-dir|--namespace|--super-prefix|--work-tree)
        ghis_option_arg=1
        ;;
      --git-dir=*|--work-tree=*|--namespace=*|--super-prefix=*)
        ;;
      --)
        ;;
      -*)
        ;;
      status|branch|rev-parse|rev-list|describe|diff|log|show|shortlog|remote|ls-files|ls-tree|cat-file|check-ignore|check-attr|for-each-ref|symbolic-ref|name-rev|count-objects|version|help)
        return 0
        ;;
      *)
        return 1
        ;;
    esac
  done
  return 1
}}

git() {{
  if [[ ${{GHIS_BYPASS:-0}} == 1 || ${{GHIS_WRAPPER_ACTIVE:-0}} == 1 ]]; then
    command git "$@"
    return $?
  fi
  if ghis_git_read_only "$@"; then
    command git "$@"
    return $?
  fi
  ghis_dispatch git "$@"
}}

gh() {{
  ghis_dispatch gh "$@"
}}

codex() {{
  if [[ ${{GHIS_BYPASS:-0}} == 1 || ${{GHIS_AGENT_WRAPPER_ACTIVE:-0}} == 1 ]]; then
    command codex "$@"
    return $?
  fi
  if ! command -v {binary} >/dev/null 2>&1; then
    command codex "$@"
    return $?
  fi
  GHIS_AGENT_WRAPPER_ACTIVE=1 command {binary} agent run codex -- "$@"
}}

# Bash has no directory-change hook. Check PWD immediately before each prompt;
# this preserves existing PROMPT_COMMAND contents instead of replacing them.
ghis_chpwd() {{
  [[ ${{GHIS_DISABLE_CHPWD:-0}} == 1 ]] && return 0
  GHIS_BYPASS=1 command {binary} status --shell >/dev/null 2>&1 || return 0
}}

ghis_prompt_command() {{
  local ghis_previous_status=$?
  if [[ ${{GHIS_LAST_PWD-}} != "$PWD" ]]; then
    GHIS_LAST_PWD=$PWD
    ghis_chpwd
  fi
  return "$ghis_previous_status"
}}

if ! declare -p PROMPT_COMMAND 2>/dev/null | grep -Fq 'ghis_prompt_command'; then
  if declare -p PROMPT_COMMAND 2>/dev/null | grep -q '^declare -a'; then
    PROMPT_COMMAND+=(ghis_prompt_command)
  elif [[ -n ${{PROMPT_COMMAND-}} ]]; then
    PROMPT_COMMAND=${{PROMPT_COMMAND}}$'\n'ghis_prompt_command
  else
    PROMPT_COMMAND=ghis_prompt_command
  fi
fi
ghis_chpwd

# Set this last so children distinguish a partial load from a complete wrapper.
export GHIS_SHELL_INTEGRATION_HEALTH=bash-v1
"#
    )
}

/// Compatibility name for callers that describe the generated source as a
/// wrapper script.
pub fn bash_wrapper_script(binary: &str) -> String {
    bash_init_script(binary)
}

/// Compatibility name used by setup and diagnostics.
pub fn generate_init(binary: &str) -> String {
    bash_init_script(binary)
}

/// Classify inherited Bash integration markers.
pub fn integration_health() -> IntegrationHealth {
    let loaded = std::env::var_os(LOADED_ENV).as_deref() == Some(OsStr::new("1"));
    let healthy = std::env::var_os(HEALTH_ENV).as_deref() == Some(OsStr::new(HEALTHY_MARKER));
    match (loaded, healthy) {
        (_, true) => IntegrationHealth::Healthy,
        (true, false) => IntegrationHealth::Incomplete,
        (false, false) => IntegrationHealth::NotLoaded,
    }
}

/// Compatibility predicate for callers that only need the loaded marker.
pub fn integration_is_loaded() -> bool {
    std::env::var_os(LOADED_ENV).as_deref() == Some(OsStr::new("1"))
}

/// Check that both generated files exactly match the integration ghis installs.
pub fn integration_is_installed(bashrc: &Path, init_file: &Path, binary: &str) -> bool {
    let expected_init = bash_init_script(binary);
    let expected_block = managed_block(init_file);
    fs::read_to_string(init_file).ok().as_deref() == Some(expected_init.as_str())
        && fs::read_to_string(bashrc)
            .ok()
            .is_some_and(|contents| contents.contains(expected_block.trim_end()))
}

/// Render the Bash completion source for ghis itself.
pub fn bash_completion_script(command: &mut Command, binary: &str) -> Vec<u8> {
    let mut output = Vec::new();
    generate(Shell::Bash, command, binary, &mut output);
    output
}

/// Render the managed source block inserted into `.bashrc`.
pub fn managed_block(init_file: &Path) -> String {
    format!(
        "{START_MARKER}\nif [[ -r {path} ]]; then\n  source {path}\nfi\n{END_MARKER}",
        path = shell_quote(&init_file.to_string_lossy())
    )
}

/// Remove every complete Bash block owned by ghis, retaining malformed blocks.
pub fn remove_managed_blocks(contents: &str) -> (String, bool) {
    managed_block_file().remove_from(contents)
}

/// Replace ghis's block while preserving unrelated startup-file content.
pub fn replace_managed_block(contents: &str, block: &str) -> String {
    ManagedBlock::new(START_MARKER, END_MARKER, block.to_owned()).replace_in(contents)
}

fn managed_block_file() -> ManagedBlock {
    ManagedBlock::new(START_MARKER, END_MARKER, String::new())
}

/// Install generated Bash source and its `.bashrc` source block transactionally.
pub fn setup(
    bashrc: impl AsRef<Path>,
    init_file: impl AsRef<Path>,
    binary: &str,
) -> io::Result<SetupReport> {
    setup_rendered(bashrc, init_file, &bash_init_script(binary))
}

/// Install already-rendered Bash source without regenerating shell syntax.
pub fn setup_rendered(
    bashrc: impl AsRef<Path>,
    init_file: impl AsRef<Path>,
    init_script: &str,
) -> io::Result<SetupReport> {
    let init_file = init_file.as_ref();
    let block = ManagedBlock::new(START_MARKER, END_MARKER, managed_block(init_file));
    let report = managed_file::setup(bashrc.as_ref(), init_file, init_script, &block)?;
    Ok(SetupReport {
        zshrc: report.zshrc,
        init_file: report.init_file,
        backup: report.backup,
        changed: report.changed,
    })
}

/// Remove ghis's managed Bash block, retaining generated source and backup.
pub fn uninstall(bashrc: impl AsRef<Path>) -> io::Result<bool> {
    managed_file::uninstall(bashrc.as_ref(), &managed_block_file())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    #[cfg(unix)]
    use std::process::Command as ProcessCommand;

    #[test]
    fn quote_handles_posix_shell_metacharacters() {
        assert_eq!(shell_quote(""), "''");
        assert_eq!(shell_quote("a'b $HOME\n🙂"), "'a'\\''b $HOME\n🙂'");
    }

    #[test]
    fn startup_target_is_home_bashrc() {
        assert_eq!(
            bashrc_path(Path::new("/home/alice")),
            PathBuf::from("/home/alice/.bashrc")
        );
    }

    #[test]
    fn generated_wrapper_is_interactive_only_and_uses_no_eval() {
        let script = bash_init_script("/tmp/a path/ghis");
        assert!(script.contains("case $- in\n  *i*) ;;\n  *) return 0 ;;"));
        assert!(script.contains("GHIS_WRAPPER_ACTIVE=1 command '/tmp/a path/ghis'"));
        assert!(script.contains("-- \"$@\""));
        assert!(script.contains("PROMPT_COMMAND+=(ghis_prompt_command)"));
        assert!(script.contains("PROMPT_COMMAND=${PROMPT_COMMAND}$'\\n'ghis_prompt_command"));
        assert!(!script.contains("eval "));
        assert!(!script.contains("add-zsh-hook"));
    }

    #[test]
    fn replacement_setup_noop_and_uninstall_are_reversible() {
        let directory = tempfile::tempdir().expect("tempdir");
        let bashrc = directory.path().join(".bashrc");
        let init = directory.path().join("config/init.bash");
        fs::write(&bashrc, "export TEST=1\n").expect("bashrc");

        let first = setup(&bashrc, &init, "ghis").expect("first setup");
        assert!(first.changed);
        assert!(first.backup.is_some());
        assert!(integration_is_installed(&bashrc, &init, "ghis"));
        let second = setup(&bashrc, &init, "ghis").expect("second setup");
        assert!(!second.changed);
        assert!(uninstall(&bashrc).expect("uninstall"));
        assert_eq!(fs::read_to_string(&bashrc).unwrap(), "export TEST=1\n");
        assert!(!uninstall(&bashrc).expect("second uninstall"));
    }

    #[test]
    fn replacement_leaves_malformed_blocks_intact() {
        let malformed = format!("before\n{START_MARKER}\ntruncated\n");
        assert_eq!(remove_managed_blocks(&malformed), (malformed, false));
    }

    #[cfg(unix)]
    #[test]
    fn bash_subprocess_keeps_noninteractive_shell_unmodified() {
        let directory = tempfile::tempdir().expect("tempdir");
        let init = directory.path().join("init.bash");
        fs::write(&init, bash_init_script("ghis")).expect("init");
        let output = ProcessCommand::new("bash")
            .args(["-n"])
            .arg(&init)
            .output()
            .expect("bash syntax");
        assert!(
            output.status.success(),
            "{}",
            String::from_utf8_lossy(&output.stderr)
        );

        let output = ProcessCommand::new("bash")
            .args(["--noprofile", "--norc", "-c", "source \"$1\"; type -t git"])
            .arg("bash")
            .arg(&init)
            .output()
            .expect("noninteractive bash");
        assert!(
            output.status.success(),
            "{}",
            String::from_utf8_lossy(&output.stderr)
        );
        assert_eq!(String::from_utf8_lossy(&output.stdout).trim(), "file");
    }

    #[cfg(unix)]
    #[test]
    fn interactive_bash_preserves_existing_prompt_command_and_git_status() {
        let directory = tempfile::tempdir().expect("tempdir");
        let fake_bin = directory.path().join("bin");
        fs::create_dir_all(&fake_bin).expect("bin");
        let fake_ghis = fake_bin.join("ghis");
        fs::write(&fake_ghis, "#!/bin/sh\nif [ \"$1\" = git ]; then shift; [ \"$1\" = -- ] && shift; command git \"$@\"; else exit 64; fi\n")
            .expect("fake ghis");
        #[cfg(unix)]
        {
            {
                use std::os::unix::fs::PermissionsExt;
                fs::set_permissions(&fake_ghis, fs::Permissions::from_mode(0o755)).expect("chmod");
            }
        }
        let init = directory.path().join("init.bash");
        fs::write(&init, bash_init_script(&fake_ghis.to_string_lossy())).expect("init");
        let output = ProcessCommand::new("bash")
            .args([
                "--noprofile",
                "--norc",
                "-ic",
                "PROMPT_COMMAND='printf preserved'; source \"$1\"; printf '|%s|\\n' \"$PROMPT_COMMAND\"; git definitely-not-a-command; printf 'status=%s\\n' \"$?\"",
                "bash",
            ])
            .arg(&init)
            .current_dir(directory.path())
            .output()
            .expect("interactive bash");
        assert!(
            output.status.success(),
            "{}",
            String::from_utf8_lossy(&output.stderr)
        );
        let stdout = String::from_utf8_lossy(&output.stdout);
        assert!(stdout.contains("printf preserved"), "{stdout}");
        assert!(stdout.contains("ghis_prompt_command"), "{stdout}");
        assert!(stdout.contains("status=1"), "{stdout}");
    }
}
