//! fish-specific rendering and persistent integration for `ghis`.
//!
//! fish loads every `*.fish` file in `~/.config/fish/conf.d/` automatically.
//! The integration therefore owns one complete drop-in instead of editing the
//! user's `config.fish`. The drop-in is written through `DropInFile`, which
//! follows an existing symlink to its regular target and rejects a dangling
//! symlink rather than replacing it.

use clap::Command;
use clap_complete::{Shell, generate};
use std::ffi::{OsStr, OsString};
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use crate::managed_file::DropInFile;

use super::zsh::{IntegrationHealth, SetupReport};
use super::{ShellKind, ShellRenderer, ShellSpec, private};

pub(super) struct FishRenderer;

impl private::Sealed for FishRenderer {}

impl ShellRenderer for FishRenderer {
    fn spec(&self) -> ShellSpec {
        ShellKind::Fish.spec()
    }

    fn render_init(&self, binary: &str) -> String {
        fish_init_script(binary)
    }

    fn render_completion(&self, command: &mut Command, binary: &str) -> Vec<u8> {
        let mut output = Vec::new();
        generate(Shell::Fish, command, binary, &mut output);
        output
    }

    fn startup_file(&self, home: &Path) -> PathBuf {
        fish_conf_d_path_from(home, std::env::var_os("XDG_CONFIG_HOME").as_deref())
    }

    fn install(
        &self,
        startup_file: &Path,
        _init_file: &Path,
        init_script: &str,
    ) -> io::Result<SetupReport> {
        setup_rendered(startup_file, init_script)
    }

    fn uninstall(&self, startup_file: &Path) -> io::Result<bool> {
        uninstall(startup_file)
    }

    fn integration_is_loaded(&self) -> bool {
        integration_is_loaded()
    }

    fn integration_health(&self) -> IntegrationHealth {
        integration_health()
    }

    fn healthy_marker(&self) -> &'static str {
        HEALTHY_MARKER
    }

    fn inherited_health_marker(&self) -> Option<OsString> {
        std::env::var_os(HEALTH_ENV)
    }

    fn integration_is_installed(
        &self,
        startup_file: &Path,
        _init_file: &Path,
        binary: &str,
    ) -> bool {
        integration_is_installed(startup_file, binary)
    }

    fn setup_command(&self) -> &'static str {
        "ghis shell setup fish"
    }
}

pub(super) static RENDERER: FishRenderer = FishRenderer;

/// Start marker for the complete fish drop-in owned by ghis.
pub const START_MARKER: &str = "# >>> ghis shell setup fish >>>";
/// End marker for the complete fish drop-in owned by ghis.
pub const END_MARKER: &str = "# <<< ghis shell setup fish <<<";
/// Exported when fish sourced the integration.
pub const LOADED_ENV: &str = "GHIS_SHELL_INTEGRATION";
/// Versioned health marker, set only after every function and event hook exists.
pub const HEALTH_ENV: &str = "GHIS_SHELL_INTEGRATION_HEALTH";
/// Health marker emitted by the current fish integration.
pub const HEALTHY_MARKER: &str = "fish-v1";

/// Resolve the one fish drop-in owned by ghis. `config.fish` is never edited.
///
/// Fish follows `XDG_CONFIG_HOME` when it is an absolute, non-empty directory;
/// otherwise it uses the standard `$HOME/.config` fallback.
pub fn fish_conf_d_path(home: &Path) -> PathBuf {
    fish_conf_d_path_from(home, std::env::var_os("XDG_CONFIG_HOME").as_deref())
}

/// Testable form of [`fish_conf_d_path`] with an explicit XDG value.
pub fn fish_conf_d_path_from(home: &Path, xdg_config_home: Option<&OsStr>) -> PathBuf {
    xdg_config_home
        .filter(|path| !path.is_empty())
        .map(PathBuf::from)
        .filter(|path| path.is_absolute())
        .unwrap_or_else(|| home.join(".config"))
        .join("fish/conf.d/ghis.fish")
}

/// Quote a value as one fish word.
///
/// This deliberately uses fish quoting rather than the POSIX/zsh renderer's
/// quote routine. Single quotes disable fish expansion; a backslash is needed
/// only for a backslash or a closing single quote inside that word.
pub fn fish_quote(value: &str) -> String {
    if value.is_empty() {
        return "''".into();
    }

    let mut quoted = String::with_capacity(value.len() + 2);
    quoted.push('\'');
    for character in value.chars() {
        if matches!(character, '\\' | '\'') {
            quoted.push('\\');
        }
        quoted.push(character);
    }
    quoted.push('\'');
    quoted
}

/// Render fish functions, wrappers, and the directory-change event handler.
///
/// `$argv` stays a fish list throughout the wrappers: there is no `eval`, no
/// reparsing of user input, and each argument reaches the real command as one
/// argument. `GHIS_WRAPPER_ACTIVE` prevents a wrapper from routing into itself.
pub fn fish_init_script(binary: &str) -> String {
    let binary = fish_quote(binary);
    format!(
        r#"{START_MARKER}
# Generated by ghis. Do not edit this file; rerun `ghis shell setup fish`.
# This file is a fish conf.d drop-in. ghis deliberately never edits config.fish.

set -gx {LOADED_ENV} 1
set -e {HEALTH_ENV}

function ghis_dispatch
    set -l ghis_kind $argv[1]
    set -e argv[1]
    if test "$GHIS_BYPASS" = 1; or test "$GHIS_WRAPPER_ACTIVE" = 1
        command $ghis_kind $argv
        return $status
    end
    if not type -q -- {binary}
        command $ghis_kind $argv
        return $status
    end
    set -lx GHIS_WRAPPER_ACTIVE 1
    command {binary} $ghis_kind -- $argv
end

# Read-only Git commands retain Git's ordinary argv, cwd, streams and exit code.
function ghis_git_read_only
    set -l ghis_option_arg 0
    for ghis_arg in $argv
        if test $ghis_option_arg -eq 1
            set ghis_option_arg 0
            continue
        end
        switch $ghis_arg
            case -C -c --config --exec-path --git-dir --namespace --super-prefix --work-tree
                set ghis_option_arg 1
            case '--git-dir=*' '--work-tree=*' '--namespace=*' '--super-prefix=*'
            case --
            case '-*'
            case status branch rev-parse rev-list describe diff log show shortlog remote ls-files ls-tree cat-file check-ignore check-attr for-each-ref symbolic-ref name-rev count-objects version help
                return 0
            case '*'
                return 1
        end
    end
    return 1
end

function git
    if test "$GHIS_BYPASS" = 1; or test "$GHIS_WRAPPER_ACTIVE" = 1
        command git $argv
        return $status
    end
    if ghis_git_read_only $argv
        command git $argv
        return $status
    end
    ghis_dispatch git $argv
    return $status
end

function gh
    ghis_dispatch gh $argv
    return $status
end

function codex
    if test "$GHIS_BYPASS" = 1; or test "$GHIS_AGENT_WRAPPER_ACTIVE" = 1
        command codex $argv
        return $status
    end
    if not type -q -- {binary}
        command codex $argv
        return $status
    end
    set -lx GHIS_AGENT_WRAPPER_ACTIVE 1
    command {binary} agent run codex -- $argv
    return $status
end

# PWD is a fish variable event, so it follows directory changes without a POSIX
# chpwd hook. The quiet probe is intentionally not parsed or eval'd.
function ghis_chpwd --on-variable PWD
    if test "$GHIS_DISABLE_CHPWD" = 1
        return 0
    end
    GHIS_BYPASS=1 command {binary} status --quiet >/dev/null 2>/dev/null
end
ghis_chpwd

set -gx {HEALTH_ENV} {HEALTHY_MARKER}
{END_MARKER}
"#
    )
}

/// Fish-side health visible to child processes.
pub fn integration_health() -> IntegrationHealth {
    let loaded = std::env::var_os(LOADED_ENV).as_deref() == Some(OsStr::new("1"));
    let healthy = std::env::var_os(HEALTH_ENV).as_deref() == Some(OsStr::new(HEALTHY_MARKER));
    match (loaded, healthy) {
        (_, true) => IntegrationHealth::Healthy,
        (true, false) => IntegrationHealth::Incomplete,
        (false, false) => IntegrationHealth::NotLoaded,
    }
}

/// Compatibility predicate for callers that only need the loaded bit.
pub fn integration_is_loaded() -> bool {
    std::env::var_os(LOADED_ENV).as_deref() == Some(OsStr::new("1"))
}

/// Check that the conf.d drop-in exactly matches the current generated source.
pub fn integration_is_installed(drop_in: &Path, binary: &str) -> bool {
    fs::read_to_string(drop_in).ok().as_deref() == Some(fish_init_script(binary).as_str())
}

/// Install a complete fish drop-in transactionally.
///
/// A pre-existing non-ghis `ghis.fish` is never overwritten. Repeated setup is
/// a no-op when its bytes already match. `DropInFile` writes a symlink target
/// atomically while retaining the requested symlink itself; dangling symlinks
/// fail closed before any new file is created.
pub fn setup(drop_in: impl AsRef<Path>, binary: &str) -> io::Result<SetupReport> {
    setup_rendered(drop_in.as_ref(), &fish_init_script(binary))
}

/// Install already rendered fish source without regenerating fish syntax.
pub fn setup_rendered(drop_in: &Path, init_script: &str) -> io::Result<SetupReport> {
    let drop_in = DropInFile::open(drop_in)?;
    match drop_in.read_optional()? {
        Some(existing) if existing == init_script => Ok(SetupReport {
            zshrc: drop_in.requested().to_path_buf(),
            init_file: drop_in.requested().to_path_buf(),
            backup: None,
            changed: false,
        }),
        Some(existing) if is_managed_drop_in(&existing) => {
            drop_in.write(init_script.as_bytes())?;
            Ok(SetupReport {
                zshrc: drop_in.requested().to_path_buf(),
                init_file: drop_in.requested().to_path_buf(),
                backup: None,
                changed: true,
            })
        }
        Some(_) => Err(io::Error::new(
            io::ErrorKind::AlreadyExists,
            format!(
                "refusing to overwrite unmanaged fish drop-in {}",
                drop_in.requested().display()
            ),
        )),
        None => {
            drop_in.write(init_script.as_bytes())?;
            Ok(SetupReport {
                zshrc: drop_in.requested().to_path_buf(),
                init_file: drop_in.requested().to_path_buf(),
                backup: None,
                changed: true,
            })
        }
    }
}

/// Remove the complete owned fish drop-in while never editing `config.fish`.
///
/// A regular drop-in is deleted. For a requested symlink, its resolved owned
/// target is replaced with an empty file so the user's symlink remains valid;
/// this avoids converting an intentional dotfiles link into a dangling link.
pub fn uninstall(drop_in: impl AsRef<Path>) -> io::Result<bool> {
    let drop_in = DropInFile::open(drop_in.as_ref())?;
    let Some(existing) = drop_in.read_optional()? else {
        return Ok(false);
    };
    if !is_managed_drop_in(&existing) {
        return Ok(false);
    }

    if fs::symlink_metadata(drop_in.requested())?
        .file_type()
        .is_symlink()
    {
        drop_in.write(b"")?;
    } else {
        fs::remove_file(drop_in.target())?;
    }
    Ok(true)
}

fn is_managed_drop_in(contents: &str) -> bool {
    contents.starts_with(START_MARKER) && contents.trim_end().ends_with(END_MARKER)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn quote_handles_paths_with_spaces_and_apostrophes() {
        assert_eq!(fish_quote(""), "''");
        assert_eq!(
            fish_quote("/tmp/a path/ghis'bin"),
            "'/tmp/a path/ghis\\'bin'"
        );
    }

    #[cfg(unix)]
    #[test]
    fn conf_d_path_uses_only_an_absolute_non_empty_xdg_config_home() {
        let home = Path::new("/home/alice");
        assert_eq!(
            fish_conf_d_path_from(home, Some(OsStr::new("/tmp/fish config"))),
            PathBuf::from("/tmp/fish config/fish/conf.d/ghis.fish")
        );
        assert_eq!(
            fish_conf_d_path_from(home, Some(OsStr::new("relative/config"))),
            PathBuf::from("/home/alice/.config/fish/conf.d/ghis.fish")
        );
        assert_eq!(
            fish_conf_d_path_from(home, Some(OsStr::new(""))),
            PathBuf::from("/home/alice/.config/fish/conf.d/ghis.fish")
        );
        assert_eq!(
            fish_conf_d_path_from(home, None),
            PathBuf::from("/home/alice/.config/fish/conf.d/ghis.fish")
        );
    }

    #[test]
    fn generated_source_uses_fish_lists_events_and_no_eval() {
        let script = fish_init_script("/tmp/a path/ghis'bin");
        assert!(script.starts_with(START_MARKER));
        assert!(script.trim_end().ends_with(END_MARKER));
        assert!(script.contains("function ghis_chpwd --on-variable PWD"));
        assert!(script.contains("set -e argv[1]"));
        assert!(script.contains("command '/tmp/a path/ghis\\'bin' $ghis_kind -- $argv"));
        assert!(script.contains("return $status"));
        assert!(!script.contains("eval "));
        assert!(!script.contains("shell_quote"));
    }

    #[test]
    fn drop_in_setup_is_exact_no_op_and_uninstall_is_reversible() {
        let directory = tempfile::tempdir().expect("tempdir");
        let drop_in = directory.path().join(".config/fish/conf.d/ghis.fish");
        let script = fish_init_script("ghis");

        let first = setup_rendered(&drop_in, &script).expect("first setup");
        assert!(first.changed);
        assert_eq!(first.zshrc, drop_in);
        assert_eq!(fs::read_to_string(&drop_in).unwrap(), script);
        let second = setup_rendered(&drop_in, &script).expect("no-op setup");
        assert!(!second.changed);
        assert!(integration_is_installed(&drop_in, "ghis"));
        assert!(uninstall(&drop_in).expect("uninstall"));
        assert!(!drop_in.exists());
        assert!(!uninstall(&drop_in).expect("uninstall no-op"));
    }

    #[test]
    fn setup_refuses_an_unmanaged_drop_in() {
        let directory = tempfile::tempdir().expect("tempdir");
        let drop_in = directory.path().join("ghis.fish");
        fs::write(&drop_in, "echo user-owned\n").expect("unmanaged drop-in");

        let error = setup(&drop_in, "ghis").expect_err("must not overwrite user file");
        assert_eq!(error.kind(), io::ErrorKind::AlreadyExists);
        assert_eq!(fs::read_to_string(&drop_in).unwrap(), "echo user-owned\n");
    }

    #[cfg(unix)]
    #[test]
    fn symlink_drop_in_retains_the_link_on_setup_and_uninstall() {
        use std::os::unix::fs::symlink;

        let directory = tempfile::tempdir().expect("tempdir");
        let target = directory.path().join("dotfiles/ghis.fish");
        fs::create_dir_all(target.parent().unwrap()).expect("target directory");
        fs::write(&target, fish_init_script("ghis")).expect("target");
        let drop_in = directory.path().join(".config/fish/conf.d/ghis.fish");
        fs::create_dir_all(drop_in.parent().unwrap()).expect("drop-in directory");
        symlink("../../../dotfiles/ghis.fish", &drop_in).expect("symlink");

        let report = setup(&drop_in, "ghis").expect("setup through symlink");
        assert!(!report.changed);
        assert!(
            fs::symlink_metadata(&drop_in)
                .unwrap()
                .file_type()
                .is_symlink()
        );
        assert!(uninstall(&drop_in).expect("uninstall through symlink"));
        assert!(
            fs::symlink_metadata(&drop_in)
                .unwrap()
                .file_type()
                .is_symlink()
        );
        assert_eq!(fs::read_to_string(target).unwrap(), "");
    }

    // This is intentionally ignored rather than treated as a passing test when
    // fish is not installed. Run it (and a real fish process) where fish exists.
    #[test]
    #[ignore = "requires the fish executable; runtime syntax validation is deferred when absent"]
    fn generated_source_passes_fish_syntax_check() {
        let directory = tempfile::tempdir().expect("tempdir");
        let source = directory.path().join("ghis.fish");
        fs::write(&source, fish_init_script("/tmp/a path/ghis'bin")).expect("source");
        let status = std::process::Command::new("fish")
            .args(["-n", source.to_str().expect("UTF-8 temp path")])
            .status()
            .expect("fish must be installed to run this ignored runtime test");
        assert!(status.success());
    }
}
