//! PowerShell-specific rendering and persistent integration for `ghis`.
//!
//! The profile contains only a small managed import block. The generated
//! `ghis.ps1` file is the replaceable drop-in, so updates never overwrite a
//! user's complete profile. PowerShell code is emitted with PowerShell single
//! quoted literals; it never evaluates a POSIX-quoted string.

use clap::Command;
use clap_complete::{Shell, generate};
use std::ffi::{OsStr, OsString};
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use crate::managed_file::{self, ManagedBlock};

use super::{IntegrationHealth, SetupReport, ShellKind, ShellRenderer, ShellSpec, private};

pub(super) struct PowerShellRenderer;

impl private::Sealed for PowerShellRenderer {}

impl ShellRenderer for PowerShellRenderer {
    fn spec(&self) -> ShellSpec {
        ShellKind::PowerShell.spec()
    }

    fn render_init(&self, binary: &str) -> String {
        powershell_init_script(binary)
    }

    fn render_completion(&self, command: &mut Command, binary: &str) -> Vec<u8> {
        let mut output = Vec::new();
        generate(Shell::PowerShell, command, binary, &mut output);
        output
    }

    fn startup_file(&self, home: &Path) -> PathBuf {
        powershell_profile_path(home)
    }

    fn install(
        &self,
        startup_file: &Path,
        init_file: &Path,
        init_script: &str,
    ) -> io::Result<SetupReport> {
        setup_rendered(startup_file, init_file, init_script)
    }

    fn uninstall(&self, startup_file: &Path) -> io::Result<bool> {
        uninstall(startup_file)
    }

    fn integration_is_loaded(&self) -> bool {
        integration_is_loaded()
    }

    fn integration_health(&self) -> IntegrationHealth {
        integration_health()
    }

    fn healthy_marker(&self) -> &'static str {
        HEALTHY_MARKER
    }

    fn inherited_health_marker(&self) -> Option<OsString> {
        std::env::var_os(HEALTH_ENV)
    }

    fn integration_is_installed(
        &self,
        startup_file: &Path,
        init_file: &Path,
        binary: &str,
    ) -> bool {
        integration_is_installed(startup_file, init_file, binary)
    }

    fn setup_command(&self) -> &'static str {
        "ghis shell setup powershell"
    }
}

pub(super) static RENDERER: PowerShellRenderer = PowerShellRenderer;

/// Markers delimit the sole portion of a PowerShell profile owned by ghis.
pub const START_MARKER: &str = "# >>> ghis PowerShell setup >>>";
pub const END_MARKER: &str = "# <<< ghis PowerShell setup <<<";
pub const LOADED_ENV: &str = "GHIS_SHELL_INTEGRATION";
pub const HEALTH_ENV: &str = "GHIS_SHELL_INTEGRATION_HEALTH";
pub const HEALTHY_MARKER: &str = "powershell-v1";

/// Resolve the PowerShell 7 current-user current-host profile.
///
/// This deliberately targets the `PowerShell` profile directory used by `pwsh`,
/// not Windows PowerShell 5.1's `WindowsPowerShell` directory. When `pwsh` is
/// absent the files remain an inert deferred installation; no Rust-side shim or
/// claim of a running PowerShell integration is made.
pub fn powershell_profile_path(home: &Path) -> PathBuf {
    home.join("Documents")
        .join("PowerShell")
        .join("Microsoft.PowerShell_profile.ps1")
}

/// Render a single PowerShell literal.
///
/// PowerShell single-quoted strings do not expand variables or substitutions.
/// An embedded quote is represented by a doubled quote. This is intentionally
/// separate from POSIX shell quoting: source paths and command paths must never
/// be rendered through a POSIX quote/eval boundary.
pub fn powershell_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "''"))
}

fn powershell_path_literal(path: &Path) -> io::Result<String> {
    let value = path.to_str().ok_or_else(|| {
        io::Error::new(
            io::ErrorKind::InvalidInput,
            "PowerShell integration requires a Unicode profile and init path",
        )
    })?;
    Ok(powershell_quote(value))
}

/// Return the generated PowerShell wrapper source.
///
/// Invocation uses PowerShell's call operator and splatted argument arrays.
/// Consequently an argv element remains one argv element—even when it contains
/// spaces, quotes, or backslashes—and no user input is parsed as shell code.
pub fn powershell_init_script(binary: &str) -> String {
    let binary = powershell_quote(binary);
    format!(
        r#"# Generated by ghis. Do not edit this file; rerun `ghis shell setup powershell`.
# This file is loaded by a managed profile import. It requires pwsh at runtime;
# when pwsh is unavailable, installation is deferred and no integration is active.

$env:GHIS_SHELL_INTEGRATION = '1'
Remove-Item Env:GHIS_SHELL_INTEGRATION_HEALTH -ErrorAction SilentlyContinue

function ghis_application_path {{
    param([Parameter(Mandatory = $true)] [string] $GhisKind)

    $ghisApplication = Get-Command -Name $GhisKind -CommandType Application -ErrorAction SilentlyContinue |
        Select-Object -First 1
    if ($null -eq $ghisApplication -or [string]::IsNullOrWhiteSpace($ghisApplication.Path)) {{
        Write-Error -Category ObjectNotFound -Message "ghis: no external application found for $GhisKind"
        $global:LASTEXITCODE = 127
        return
    }}
    $ghisApplication.Path
}}

function ghis_dispatch {{
    param(
        [Parameter(Mandatory = $true, Position = 0)] [string] $GhisKind,
        [Parameter(ValueFromRemainingArguments = $true)] [object[]] $GhisArguments
    )

    # Resolve the external application before every direct path. The wrappers
    # below have the same names, so resolving a command name directly recurses.
    $ghisApplicationPath = ghis_application_path $GhisKind
    if ([string]::IsNullOrWhiteSpace($ghisApplicationPath)) {{
        return
    }}

    if ($env:GHIS_BYPASS -eq '1' -or $env:GHIS_WRAPPER_ACTIVE -eq '1') {{
        & $ghisApplicationPath @GhisArguments
        return
    }}

    $ghisProgram = Get-Command -Name {binary} -CommandType Application -ErrorAction SilentlyContinue |
        Select-Object -First 1
    if ($null -eq $ghisProgram -or [string]::IsNullOrWhiteSpace($ghisProgram.Path)) {{
        & $ghisApplicationPath @GhisArguments
        return
    }}

    $ghisPreviousWrapperActive = $env:GHIS_WRAPPER_ACTIVE
    $env:GHIS_WRAPPER_ACTIVE = '1'
    try {{
        & $ghisProgram.Path $GhisKind -- @GhisArguments
    }}
    finally {{
        if ($null -eq $ghisPreviousWrapperActive) {{
            Remove-Item Env:GHIS_WRAPPER_ACTIVE -ErrorAction SilentlyContinue
        }}
        else {{
            $env:GHIS_WRAPPER_ACTIVE = $ghisPreviousWrapperActive
        }}
    }}
}}

function git {{
    param([Parameter(ValueFromRemainingArguments = $true)] [object[]] $GhisArguments)
    ghis_dispatch git @GhisArguments
}}

function gh {{
    param([Parameter(ValueFromRemainingArguments = $true)] [object[]] $GhisArguments)
    ghis_dispatch gh @GhisArguments
}}

# Do not replace `prompt`, `Set-Location`, or location-change hooks. A user
# prompt therefore remains in charge of its own state and output.
$env:GHIS_SHELL_INTEGRATION_HEALTH = 'powershell-v1'
"#
    )
}

/// Render the profile's managed import block. Non-Unicode paths fail closed:
/// lossy conversion could source a path distinct from the file Rust wrote.
pub fn managed_block(init_file: &Path) -> io::Result<String> {
    let path = powershell_path_literal(init_file)?;
    Ok(format!(
        "{START_MARKER}\nif (Test-Path -LiteralPath {path} -PathType Leaf) {{\n    . {path}\n}}\n{END_MARKER}"
    ))
}

fn managed_block_file() -> ManagedBlock {
    ManagedBlock::new(START_MARKER, END_MARKER, String::new())
}

/// Classify the environment advertised by the parent PowerShell process.
pub fn integration_health() -> IntegrationHealth {
    let loaded = std::env::var_os(LOADED_ENV).as_deref() == Some(OsStr::new("1"));
    let healthy = std::env::var_os(HEALTH_ENV).as_deref() == Some(OsStr::new(HEALTHY_MARKER));
    match (loaded, healthy) {
        (_, true) => IntegrationHealth::Healthy,
        (true, false) => IntegrationHealth::Incomplete,
        (false, false) => IntegrationHealth::NotLoaded,
    }
}

pub fn integration_is_loaded() -> bool {
    std::env::var_os(LOADED_ENV).as_deref() == Some(OsStr::new("1"))
}

/// Check both durable files against the exact source this renderer now emits.
pub fn integration_is_installed(profile: &Path, init_file: &Path, binary: &str) -> bool {
    let Ok(expected_block) = managed_block(init_file) else {
        return false;
    };
    fs::read_to_string(init_file).ok().as_deref() == Some(powershell_init_script(binary).as_str())
        && fs::read_to_string(profile)
            .ok()
            .is_some_and(|contents| contents.contains(expected_block.trim_end()))
}

pub fn setup(
    profile: impl AsRef<Path>,
    init_file: impl AsRef<Path>,
    binary: &str,
) -> io::Result<SetupReport> {
    setup_rendered(profile, init_file, &powershell_init_script(binary))
}

/// Install the drop-in script and profile import as one managed-file transaction.
pub fn setup_rendered(
    profile: impl AsRef<Path>,
    init_file: impl AsRef<Path>,
    init_script: &str,
) -> io::Result<SetupReport> {
    let init_file = init_file.as_ref();
    let block = ManagedBlock::new(START_MARKER, END_MARKER, managed_block(init_file)?);
    let report = managed_file::setup(profile.as_ref(), init_file, init_script, &block)?;
    Ok(SetupReport {
        zshrc: report.zshrc,
        init_file: report.init_file,
        backup: report.backup,
        changed: report.changed,
    })
}

/// Remove the profile import but retain the drop-in and the original backup.
pub fn uninstall(profile: impl AsRef<Path>) -> io::Result<bool> {
    managed_file::uninstall(profile.as_ref(), &managed_block_file())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    #[test]
    fn quote_uses_powershell_single_quoted_literals() {
        assert_eq!(powershell_quote(""), "''");
        assert_eq!(powershell_quote("C:\\a b\\O'Hara"), "'C:\\a b\\O''Hara'");
        assert_eq!(powershell_quote("$HOME; & nope"), "'$HOME; & nope'");
    }

    #[test]
    fn managed_import_preserves_spaces_quotes_and_backslashes() {
        let init = Path::new(r"C:\Users\O'Hara Smith\.config\ghis\ghis.ps1");
        let block = managed_block(init).expect("Unicode path");
        assert!(block.contains("-LiteralPath 'C:\\Users\\O''Hara Smith\\.config\\ghis\\ghis.ps1'"));
        assert!(block.contains(". 'C:\\Users\\O''Hara Smith\\.config\\ghis\\ghis.ps1'"));
        assert!(!block.contains("Invoke-Expression"));
    }

    #[test]
    fn script_has_recursion_guard_and_does_not_own_prompt_or_location() {
        let script = powershell_init_script(r"C:\Program Files\O'Hara\ghis.exe");
        assert!(script.contains("Get-Command -Name $GhisKind -CommandType Application"));
        assert!(script.contains(
            "Get-Command -Name 'C:\\Program Files\\O''Hara\\ghis.exe' -CommandType Application"
        ));
        assert!(script.contains("& $ghisApplicationPath @GhisArguments"));
        assert!(script.contains("& $ghisProgram.Path $GhisKind -- @GhisArguments"));
        assert!(script.contains("GHIS_WRAPPER_ACTIVE"));
        assert!(script.contains("[object[]] $GhisArguments"));
        assert!(script.contains("$global:LASTEXITCODE = 127"));
        assert!(!script.contains("& $GhisKind @GhisArguments"));
        assert!(!script.contains("return $LASTEXITCODE"));
        assert!(!script.contains("Invoke-Expression"));
        assert!(!script.contains("function prompt"));
        assert!(!script.contains("function Set-Location"));
    }

    #[test]
    fn profile_target_is_pwsh_current_user_current_host() {
        assert_eq!(
            powershell_profile_path(Path::new("C:/Users/alice")),
            PathBuf::from("C:/Users/alice/Documents/PowerShell/Microsoft.PowerShell_profile.ps1")
        );
    }

    #[test]
    fn setup_is_idempotent_and_uninstall_handles_lf_and_crlf_profiles() {
        for (name, initial, expected) in [
            ("lf", "$env:USER_VALUE = 'x'\n", "$env:USER_VALUE = 'x'\n"),
            (
                "crlf",
                "$env:USER_VALUE = 'x'\r\n",
                "$env:USER_VALUE = 'x'\r\n",
            ),
        ] {
            let directory = tempfile::tempdir().expect(name);
            let profile = directory.path().join("profile.ps1");
            let init = directory.path().join("ghis.ps1");
            fs::write(&profile, initial).expect("profile");

            let first = setup(&profile, &init, "ghis").expect("setup");
            assert!(first.changed);
            assert!(integration_is_installed(&profile, &init, "ghis"));
            assert!(
                !setup(&profile, &init, "ghis")
                    .expect("repeat setup")
                    .changed
            );
            assert!(uninstall(&profile).expect("uninstall"));
            assert_eq!(fs::read_to_string(&profile).unwrap(), expected);
            assert!(!uninstall(&profile).expect("repeat uninstall"));
        }
    }

    #[test]
    fn setup_creates_a_missing_profile_and_fails_closed_for_invalid_utf8() {
        let directory = tempfile::tempdir().expect("tempdir");
        let profile = directory.path().join("nested/profile.ps1");
        let init = directory.path().join("ghis.ps1");
        assert!(
            setup(&profile, &init, "ghis")
                .expect("missing profile")
                .changed
        );
        assert!(profile.exists());

        let invalid = directory.path().join("invalid.ps1");
        let old_init = directory.path().join("old.ps1");
        fs::write(&invalid, [b'#', 0xff, b'\n']).expect("invalid profile");
        fs::write(&old_init, "old init\n").expect("old init");
        assert!(setup(&invalid, &old_init, "ghis").is_err());
        assert_eq!(fs::read_to_string(&old_init).unwrap(), "old init\n");
    }

    #[cfg(windows)]
    #[test]
    #[ignore = "runtime-deferred: requires pwsh; Windows CI runs this explicitly"]
    fn pwsh_parses_wrapper_and_preserves_git_stdout_and_exit_status() {
        use std::process::Command;

        let directory = tempfile::tempdir().expect("tempdir");
        let init = directory.path().join("ghis.ps1");
        let driver = directory.path().join("driver.ps1");
        fs::write(&init, powershell_init_script("ghis")).expect("init script");
        fs::write(
            &driver,
            format!(
                ". {}\n$env:GHIS_BYPASS = '1'\ngit --version\nexit $LASTEXITCODE\n",
                powershell_quote(init.to_str().expect("Unicode test path"))
            ),
        )
        .expect("driver script");

        let output = Command::new("pwsh")
            .args(["-NoProfile", "-NonInteractive", "-File"])
            .arg(&driver)
            .output()
            .expect("pwsh is required for the explicit Windows runtime test");
        assert!(
            output.status.success(),
            "{}",
            String::from_utf8_lossy(&output.stderr)
        );
        let stdout = String::from_utf8(output.stdout).expect("git stdout is UTF-8");
        assert!(stdout.starts_with("git version "), "{stdout:?}");
        assert_eq!(
            stdout.lines().count(),
            1,
            "wrapper must not append an exit code"
        );

        let failing_driver = directory.path().join("failing-driver.ps1");
        fs::write(
            &failing_driver,
            format!(
                ". {}\n$env:GHIS_BYPASS = '1'\ngit definitely-not-a-ghis-test-command\nexit $LASTEXITCODE\n",
                powershell_quote(init.to_str().expect("Unicode test path"))
            ),
        )
        .expect("failing driver");
        let failure = Command::new("pwsh")
            .args(["-NoProfile", "-NonInteractive", "-File"])
            .arg(failing_driver)
            .output()
            .expect("pwsh is required for the explicit Windows runtime test");
        assert!(!failure.status.success());
        assert!(
            failure.stdout.is_empty(),
            "wrapper must not print an exit code"
        );
    }

    #[cfg(windows)]
    #[test]
    fn windows_profile_path_uses_the_pwsh_current_user_current_host_location() {
        let profile = powershell_profile_path(Path::new(r"C:\Users\Alice"));
        assert!(profile.ends_with(r"Documents\PowerShell\Microsoft.PowerShell_profile.ps1"));
    }
}
