//! zsh-specific rendering and persistent integration for `ghis`.
//!
//! This module owns zsh source bytes and zsh startup-file behavior.  The parent
//! `shell` module intentionally exposes the stable `ghis::shell::*` facade.

use clap::Command;
use clap_complete::{Shell, generate};
use std::ffi::{OsStr, OsString};
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use crate::managed_file::{self, ManagedBlock};

use super::{ShellKind, ShellRenderer, ShellSpec, private};

pub(super) struct ZshRenderer;

impl private::Sealed for ZshRenderer {}

impl ShellRenderer for ZshRenderer {
    fn spec(&self) -> ShellSpec {
        ShellKind::Zsh.spec()
    }

    fn render_init(&self, binary: &str) -> String {
        zsh_init_script(binary)
    }

    fn render_completion(&self, command: &mut Command, binary: &str) -> Vec<u8> {
        let mut output = Vec::new();
        generate(Shell::Zsh, command, binary, &mut output);
        output
    }

    fn startup_file(&self, home: &Path) -> PathBuf {
        zshrc_path(home, std::env::var_os("ZDOTDIR").as_deref())
    }

    fn install(
        &self,
        startup_file: &Path,
        init_file: &Path,
        init_script: &str,
    ) -> io::Result<SetupReport> {
        setup_rendered(startup_file, init_file, init_script)
    }

    fn uninstall(&self, startup_file: &Path) -> io::Result<bool> {
        uninstall(startup_file)
    }

    fn integration_is_loaded(&self) -> bool {
        integration_is_loaded()
    }

    fn integration_health(&self) -> IntegrationHealth {
        integration_health()
    }

    fn healthy_marker(&self) -> &'static str {
        HEALTHY_MARKER
    }

    fn inherited_health_marker(&self) -> Option<OsString> {
        std::env::var_os(HEALTH_ENV)
    }

    fn integration_is_installed(
        &self,
        startup_file: &Path,
        init_file: &Path,
        binary: &str,
    ) -> bool {
        integration_is_installed(startup_file, init_file, binary)
    }

    fn setup_command(&self) -> &'static str {
        "ghis setup"
    }
}

pub(super) static RENDERER: ZshRenderer = ZshRenderer;

/// Start marker for the block owned by ghis in a zsh startup file.
pub const START_MARKER: &str = "# >>> ghis setup >>>";
/// End marker for the block owned by ghis in a zsh startup file.
pub const END_MARKER: &str = "# <<< ghis setup <<<";
/// Exported by the generated init script so child `ghis` processes can tell
/// that this shell sourced some version of the wrapper.
pub const LOADED_ENV: &str = "GHIS_SHELL_INTEGRATION";
/// Versioned shell-side health marker. Rust cannot inspect functions in its
/// parent shell, so a generated init script only advertises a complete wrapper
/// after all functions and hook dependencies have been defined.
pub const HEALTH_ENV: &str = "GHIS_SHELL_INTEGRATION_HEALTH";
/// Health marker emitted by the current generated integration.
pub const HEALTHY_MARKER: &str = "zsh-v3";

/// Resolve the zsh startup file using the same `ZDOTDIR` convention as zsh.
pub fn zshrc_path(home: &Path, zdotdir: Option<&OsStr>) -> PathBuf {
    zdotdir
        .filter(|value| !value.is_empty())
        .map(PathBuf::from)
        .unwrap_or_else(|| home.to_path_buf())
        .join(".zshrc")
}

/// Result of installing the shell integration.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SetupReport {
    /// Startup file that was updated.
    pub zshrc: PathBuf,
    /// Generated init file sourced by the startup file.
    pub init_file: PathBuf,
    /// Backup created before the first modification, if any.
    pub backup: Option<PathBuf>,
    /// Whether either file was changed.
    pub changed: bool,
}

/// Quote a value for use as a single zsh argument.
///
/// A single quoted shell word cannot interpolate variables, command
/// substitutions, backticks, globbing, or backslashes.  The only character
/// that needs escaping is a single quote, represented by closing the quote,
/// emitting `\'`, and opening it again.
pub fn shell_quote(value: &str) -> String {
    if value.is_empty() {
        return "''".to_string();
    }

    let mut quoted = String::with_capacity(value.len() + 2);
    quoted.push('\'');
    for character in value.chars() {
        if character == '\'' {
            quoted.push_str("'\\''");
        } else {
            quoted.push(character);
        }
    }
    quoted.push('\'');
    quoted
}

/// Return the generated zsh functions.
///
/// `binary` is usually `ghis`, but accepting a path makes development builds
/// and package managers work without changing the generated wrapper.  The
/// generated functions preserve stdin/stdout/stderr and the child exit code.
pub fn zsh_init_script(binary: &str) -> String {
    let binary = shell_quote(binary);
    format!(
        r#"# Generated by ghis. Do not edit this file; rerun `ghis setup`.
# The functions are intentionally wrappers, so aliases and all TTY streams
# remain owned by the caller. Set GHIS_BYPASS=1 for one command when needed.

typeset -gx GHIS_SHELL_INTEGRATION=1
unset GHIS_SHELL_INTEGRATION_HEALTH

ghis_dispatch() {{
  local ghis_kind="$1"
  shift
  if [[ "${{GHIS_BYPASS:-0}}" == 1 || "${{GHIS_WRAPPER_ACTIVE:-0}}" == 1 ]]; then
    command "$ghis_kind" "$@"
    return $?
  fi
  if ! command -v {binary} >/dev/null 2>&1; then
    command "$ghis_kind" "$@"
    return $?
  fi
  GHIS_WRAPPER_ACTIVE=1 command {binary} "$ghis_kind" -- "$@"
}}

# Keep the historical helper name for already-loaded callers and third-party
# snippets, but make the wrapper itself depend only on the snapshot-safe name.
_ghis_dispatch() {{
  ghis_dispatch "$@"
}}

# Read-only Git probes are commonly issued by prompts (status, branch and
# rev-parse). They do not need ghis identity or credential policy. Bypass the
# expensive application path for those probes; writes and network operations
# continue through ghis_dispatch below.
ghis_git_read_only() {{
  local ghis_arg
  local ghis_option_arg=0
  for ghis_arg in "$@"; do
    if (( ghis_option_arg )); then
      ghis_option_arg=0
      continue
    fi
    case "$ghis_arg" in
      -C|-c|--config|--exec-path|--git-dir|--namespace|--super-prefix|--work-tree)
        ghis_option_arg=1
        ;;
      --git-dir=*|--work-tree=*|--namespace=*|--super-prefix=*)
        ;;
      --)
        ;;
      -*)
        ;;
      status|branch|rev-parse|rev-list|describe|diff|log|show|shortlog|remote|ls-files|ls-tree|cat-file|check-ignore|check-attr|for-each-ref|symbolic-ref|name-rev|count-objects|version|help)
        return 0
        ;;
      *)
        return 1
        ;;
    esac
  done
  return 1
}}

function git {{
  if [[ "${{GHIS_BYPASS:-0}}" == 1 || "${{GHIS_WRAPPER_ACTIVE:-0}}" == 1 ]]; then
    command git "$@"
    return $?
  fi
  if ghis_git_read_only "$@"; then
    command git "$@"
    return $?
  fi
  ghis_dispatch git "$@"
}}

function gh {{
  ghis_dispatch gh "$@"
}}

# Codex has no SessionStart hook equivalent. Route an ordinary `codex` launch
# through ghis so developer instructions are rendered from the current cwd.
function codex {{
  if [[ "${{GHIS_BYPASS:-0}}" == 1 || "${{GHIS_AGENT_WRAPPER_ACTIVE:-0}}" == 1 ]]; then
    command codex "$@"
    return $?
  fi
  if ! command -v {binary} >/dev/null 2>&1; then
    command codex "$@"
    return $?
  fi
  GHIS_AGENT_WRAPPER_ACTIVE=1 command {binary} agent run codex -- "$@"
}}

# Refreshing this local state is optional and never performs network access.
# A caller can set GHIS_DISABLE_CHPWD=1 when another chpwd hook owns this work.
autoload -Uz add-zsh-hook 2>/dev/null || true
ghis_chpwd() {{
  [[ "${{GHIS_DISABLE_CHPWD:-0}}" == 1 ]] && return 0
  local ghis_silent="${{1:-0}}"
  local ghis_state
  ghis_state="$(GHIS_BYPASS=1 command {binary} status --shell 2>/dev/null)" || {{
    typeset -g GHIS_CHPWD_ENABLED=0
    typeset -g GHIS_REPO_PROFILE=''
    typeset -g GHIS_REPO_PROFILE_DISPLAY=''
    typeset -g GHIS_REPO_ROOT=''
    return 0
  }}
  eval "$ghis_state"
  typeset -g GHIS_CHPWD_ENABLED
  typeset -g GHIS_REPO_PROFILE
  typeset -g GHIS_REPO_PROFILE_DISPLAY
  typeset -g GHIS_REPO_ROOT
  if [[ "$ghis_silent" != 1 && "$GHIS_CHPWD_ENABLED" == 1 && -n "$GHIS_REPO_PROFILE" ]]; then
    print -r -- "GHIS Profile: $GHIS_REPO_PROFILE_DISPLAY"
  fi
}}
_ghis_chpwd() {{
  ghis_chpwd "$@"
}}
if (( $+functions[add-zsh-hook] )); then
  add-zsh-hook -d chpwd _ghis_chpwd 2>/dev/null || true
  add-zsh-hook -d chpwd ghis_chpwd 2>/dev/null || true
  add-zsh-hook chpwd ghis_chpwd
  ghis_chpwd 1
fi

# Set this last: children can distinguish a legacy/partial environment marker
# from a wrapper whose function dependencies were all initialized.
typeset -gx GHIS_SHELL_INTEGRATION_HEALTH=zsh-v3
"#
    )
}

/// Compatibility name for callers that describe the generated functions as a
/// wrapper script.
pub fn zsh_wrapper_script(binary: &str) -> String {
    zsh_init_script(binary)
}

/// Compatibility name used by setup/diagnostic commands.
pub fn generate_init(binary: &str) -> String {
    zsh_init_script(binary)
}

/// Shell-side health visible to child processes.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[non_exhaustive]
pub enum IntegrationHealth {
    NotLoaded,
    Incomplete,
    Healthy,
}

/// Classify the inherited shell markers. Functions themselves live in the
/// parent zsh process and cannot be queried by Rust, so the init script sets a
/// versioned health marker only after defining every dependency.
pub fn integration_health() -> IntegrationHealth {
    let loaded = std::env::var_os(LOADED_ENV).as_deref() == Some(OsStr::new("1"));
    let healthy = std::env::var_os(HEALTH_ENV).as_deref() == Some(OsStr::new(HEALTHY_MARKER));
    match (loaded, healthy) {
        (_, true) => IntegrationHealth::Healthy,
        (true, false) => IntegrationHealth::Incomplete,
        (false, false) => IntegrationHealth::NotLoaded,
    }
}

/// Compatibility predicate for callers that only need the legacy loaded bit.
pub fn integration_is_loaded() -> bool {
    std::env::var_os(LOADED_ENV).as_deref() == Some(OsStr::new("1"))
}

/// Check that both generated files still contain exactly the setup ghis would
/// install now. This is read-only and does not imply the current shell sourced
/// either file.
pub fn integration_is_installed(zshrc: &Path, init_file: &Path, binary: &str) -> bool {
    let expected_init = zsh_init_script(binary);
    let expected_block = managed_block(init_file);
    fs::read_to_string(init_file).ok().as_deref() == Some(expected_init.as_str())
        && fs::read_to_string(zshrc)
            .ok()
            .is_some_and(|contents| contents.contains(expected_block.trim_end()))
}

/// Generate zsh glue for the wrapped commands.
///
/// `git` and `gh` already have mature completion functions.  The wrapper
/// should preserve those functions instead of trying to feed their words into
/// ghis's own static completion generator.
pub fn zsh_completion_script(_binary: &str) -> String {
    r#"#compdef git gh

if (( $+functions[_git] )); then
  compdef _git git
fi
if (( $+functions[_gh] )); then
  compdef _gh gh
fi
"#
    .to_string()
}

/// Render the small source block inserted into `.zshrc`.
pub fn managed_block(init_file: &Path) -> String {
    format!(
        "{START_MARKER}\nif [[ -r {path} ]]; then\n  source {path}\nfi\n{END_MARKER}",
        path = shell_quote(&init_file.to_string_lossy())
    )
}

/// Remove every complete managed block from `contents`.
///
/// The function leaves malformed/incomplete blocks untouched.  This is
/// intentional: silently deleting a user file after a truncated write is more
/// surprising than asking the user to repair the marker manually.
pub fn remove_managed_blocks(contents: &str) -> (String, bool) {
    managed_block_file().remove_from(contents)
}

/// Replace ghis's block in a startup file, preserving unrelated text.
pub fn replace_managed_block(contents: &str, block: &str) -> String {
    ManagedBlock::new(START_MARKER, END_MARKER, block.to_string()).replace_in(contents)
}

fn managed_block_file() -> ManagedBlock {
    ManagedBlock::new(START_MARKER, END_MARKER, String::new())
}

/// Install the generated init file and managed `.zshrc` source block.
pub fn setup(
    zshrc: impl AsRef<Path>,
    init_file: impl AsRef<Path>,
    binary: &str,
) -> io::Result<SetupReport> {
    setup_rendered(zshrc, init_file, &zsh_init_script(binary))
}

/// Install already-rendered zsh source without allowing the installer to
/// regenerate shell syntax. Renderers own source; this routine owns only the
/// managed-file transaction.
pub fn setup_rendered(
    zshrc: impl AsRef<Path>,
    init_file: impl AsRef<Path>,
    init_script: &str,
) -> io::Result<SetupReport> {
    let init_file = init_file.as_ref();
    // The source path intentionally stays as requested, even if that file is a
    // symlink whose resolved target receives the generated init script.
    let block = ManagedBlock::new(START_MARKER, END_MARKER, managed_block(init_file));
    let report = managed_file::setup(zshrc.as_ref(), init_file, init_script, &block)?;
    Ok(SetupReport {
        zshrc: report.zshrc,
        init_file: report.init_file,
        backup: report.backup,
        changed: report.changed,
    })
}

/// Remove ghis's managed block from a startup file.
///
/// The generated init file and backup are intentionally retained.  They are
/// useful for recovery and deleting them would make uninstall less reversible.
pub fn uninstall(zshrc: impl AsRef<Path>) -> io::Result<bool> {
    managed_file::uninstall(zshrc.as_ref(), &managed_block_file())
}

/// Explicitly named aliases for callers that prefer operation-oriented names.
pub fn setup_zsh(
    zshrc: impl AsRef<Path>,
    init_file: impl AsRef<Path>,
    binary: &str,
) -> io::Result<SetupReport> {
    setup(zshrc, init_file, binary)
}

/// Remove the managed zsh block (the generated file is retained).
pub fn uninstall_zsh(zshrc: impl AsRef<Path>) -> io::Result<bool> {
    uninstall(zshrc)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    #[test]
    fn quote_handles_shell_metacharacters() {
        assert_eq!(shell_quote(""), "''");
        assert_eq!(shell_quote("a'b $HOME\n🙂"), "'a'\\''b $HOME\n🙂'");
    }

    #[test]
    fn zshrc_path_prefers_non_empty_zdotdir() {
        assert_eq!(
            zshrc_path(Path::new("/home/alice"), Some(OsStr::new("/tmp/zsh"))),
            PathBuf::from("/tmp/zsh/.zshrc")
        );
        assert_eq!(
            zshrc_path(Path::new("/home/alice"), Some(OsStr::new(""))),
            PathBuf::from("/home/alice/.zshrc")
        );
        assert_eq!(
            zshrc_path(Path::new("/home/alice"), None),
            PathBuf::from("/home/alice/.zshrc")
        );
    }

    #[test]
    fn generated_helpers_use_snapshot_safe_names_and_keep_legacy_aliases() {
        let script = zsh_init_script("ghis");
        assert!(script.contains("ghis_dispatch()"));
        assert!(script.contains("ghis_chpwd()"));
        assert!(script.contains("status --shell"));
        assert!(script.contains("ghis_chpwd 1"));
        assert!(script.contains("GHIS_REPO_PROFILE_DISPLAY"));
        assert!(!script.contains("typeset -g GHIS_PROFILE"));
        assert!(script.contains("_ghis_dispatch()"));
        assert!(script.contains("_ghis_chpwd()"));
        assert!(script.contains("ghis_dispatch git \"$@\""));
        assert!(script.contains("ghis_git_read_only()"));
        assert!(script.contains("status|branch|rev-parse"));
        assert!(!script.contains("|config|ls-files"));
        assert!(script.contains("GHIS Profile: $GHIS_REPO_PROFILE_DISPLAY"));
        assert!(script.contains("function codex"));
        assert!(script.contains("agent run codex -- \"$@\""));
        assert!(script.contains("GHIS_AGENT_WRAPPER_ACTIVE"));
        assert!(script.contains("GHIS_SHELL_INTEGRATION_HEALTH=zsh-v3"));
        assert!(!script.contains("__ghis_dispatch"));
    }

    #[test]
    fn replacement_is_idempotent() {
        let block = managed_block(Path::new("/tmp/a path/init.zsh"));
        let once = replace_managed_block("export A=1\n", &block);
        let twice = replace_managed_block(&once, &block);
        assert_eq!(once, twice);
        assert_eq!(once.matches(START_MARKER).count(), 1);
    }

    #[test]
    fn malformed_block_is_not_removed() {
        let input = format!("before\n{START_MARKER}\ntruncated\n");
        let (output, changed) = remove_managed_blocks(&input);
        assert!(!changed);
        assert_eq!(output, input);
    }

    #[test]
    fn replacement_preserves_content_after_an_unmatched_start() {
        let malformed = format!("before\n{START_MARKER}\nuser content\n");
        let block = managed_block(Path::new("/tmp/init.zsh"));
        let once = replace_managed_block(&malformed, &block);
        let twice = replace_managed_block(&once, &block);

        assert_eq!(twice, once);
        assert!(twice.contains("user content"));
        assert_eq!(twice.matches(START_MARKER).count(), 2);
    }

    #[test]
    fn removal_preserves_nested_malformed_block_and_orphan_end() {
        let input = format!(
            "before\n{END_MARKER}\n{START_MARKER}\nmalformed\n{START_MARKER}\nmanaged\n{END_MARKER}\nafter\n"
        );
        let (output, changed) = remove_managed_blocks(&input);

        assert!(changed);
        assert_eq!(
            output,
            format!("before\n{END_MARKER}\n{START_MARKER}\nmalformed\nafter\n")
        );
    }

    #[test]
    fn setup_and_uninstall_round_trip() {
        let directory = tempfile::tempdir().expect("tempdir");
        let zshrc = directory.path().join(".zshrc");
        let init = directory.path().join("config/init.zsh");
        fs::write(&zshrc, "export TEST=1\n").expect("write");
        let report = setup(&zshrc, &init, "ghis").expect("setup");
        assert!(report.changed);
        assert!(report.backup.is_some());
        assert!(integration_is_installed(&zshrc, &init, "ghis"));
        assert!(
            fs::read_to_string(&zshrc)
                .expect("read")
                .contains(START_MARKER)
        );
        let second = setup(&zshrc, &init, "ghis").expect("second setup");
        assert!(!second.changed);
        assert!(uninstall(&zshrc).expect("uninstall"));
        let after_uninstall = fs::read_to_string(&zshrc).expect("read");
        assert!(!after_uninstall.contains(START_MARKER));
        assert!(!integration_is_installed(&zshrc, &init, "ghis"));
        assert_eq!(after_uninstall, "export TEST=1\n");
        assert!(!uninstall(&zshrc).expect("second uninstall"));
        assert_eq!(fs::read_to_string(&zshrc).expect("read"), after_uninstall);
    }

    #[cfg(unix)]
    #[test]
    fn setup_and_uninstall_preserve_a_zshrc_symlink() {
        use std::os::unix::fs::symlink;

        let directory = tempfile::tempdir().expect("tempdir");
        let target = directory.path().join("dotfiles/zshrc");
        fs::create_dir_all(target.parent().unwrap()).expect("target directory");
        fs::write(&target, "export LINKED=1\n").expect("target");
        let zshrc = directory.path().join(".zshrc");
        symlink("dotfiles/zshrc", &zshrc).expect("symlink");
        let init = directory.path().join("config/init.zsh");

        setup(&zshrc, &init, "ghis").expect("setup through symlink");
        assert!(
            fs::symlink_metadata(&zshrc)
                .unwrap()
                .file_type()
                .is_symlink()
        );
        assert!(fs::read_to_string(&target).unwrap().contains(START_MARKER));

        assert!(uninstall(&zshrc).expect("uninstall through symlink"));
        assert!(
            fs::symlink_metadata(&zshrc)
                .unwrap()
                .file_type()
                .is_symlink()
        );
        assert_eq!(fs::read_to_string(&target).unwrap(), "export LINKED=1\n");
    }

    #[test]
    fn removal_preserves_exact_lf_and_crlf_surrounding_content() {
        let block = managed_block(Path::new("/tmp/init.zsh"));
        let lf = format!("before\n\n{block}\nafter\n");
        assert_eq!(
            remove_managed_blocks(&lf),
            ("before\nafter\n".to_string(), true)
        );

        let crlf_block = block.replace('\n', "\r\n");
        let crlf = format!("before\r\n\r\n{crlf_block}\r\nafter\r\n");
        assert_eq!(
            remove_managed_blocks(&crlf),
            ("before\r\nafter\r\n".to_string(), true)
        );
    }

    #[test]
    fn removal_removes_multiple_complete_blocks_only() {
        let block = managed_block(Path::new("/tmp/init.zsh"));
        let input = format!("before\n\n{block}\nbetween\n\n{block}\nafter\n");
        assert_eq!(
            remove_managed_blocks(&input),
            ("before\nbetween\nafter\n".to_string(), true)
        );
    }

    #[test]
    fn setup_preserves_the_first_backup_across_later_updates() {
        let directory = tempfile::tempdir().expect("tempdir");
        let zshrc = directory.path().join(".zshrc");
        let init = directory.path().join("init.zsh");
        fs::write(&zshrc, "export ORIGINAL=1\n").expect("write zshrc");

        let first = setup(&zshrc, &init, "ghis").expect("first setup");
        let backup = first.backup.expect("first backup");
        fs::write(&zshrc, "export MODIFIED=1\n").expect("modify zshrc");
        let second = setup(&zshrc, &init, "ghis").expect("second setup");

        assert!(second.changed);
        assert_eq!(second.backup, None);
        assert_eq!(fs::read_to_string(backup).unwrap(), "export ORIGINAL=1\n");
    }

    #[cfg(unix)]
    #[test]
    fn setup_sources_the_requested_init_symlink_path() {
        use std::os::unix::fs::symlink;

        let directory = tempfile::tempdir().expect("tempdir");
        let zshrc = directory.path().join(".zshrc");
        let init_target = directory.path().join("dotfiles/init.zsh");
        fs::create_dir_all(init_target.parent().unwrap()).expect("dotfiles directory");
        fs::write(&init_target, "old init\n").expect("init target");
        let requested_init = directory.path().join(".config/ghis/init.zsh");
        fs::create_dir_all(requested_init.parent().unwrap()).expect("config directory");
        symlink("../../dotfiles/init.zsh", &requested_init).expect("init symlink");

        setup(&zshrc, &requested_init, "ghis").expect("setup");
        assert_eq!(
            fs::read_to_string(&init_target).unwrap(),
            zsh_init_script("ghis")
        );
        assert!(
            fs::read_to_string(&zshrc)
                .unwrap()
                .contains(&shell_quote(&requested_init.to_string_lossy()))
        );
    }

    #[cfg(unix)]
    #[test]
    fn setup_rejects_dangling_zshrc_and_init_symlinks_without_writing() {
        use std::os::unix::fs::symlink;

        let directory = tempfile::tempdir().expect("tempdir");
        let zshrc = directory.path().join(".zshrc");
        let init = directory.path().join("init.zsh");
        symlink("missing-zshrc", &zshrc).expect("zshrc symlink");
        assert!(setup(&zshrc, &init, "ghis").is_err());
        assert!(!init.exists());
        assert!(
            fs::symlink_metadata(&zshrc)
                .unwrap()
                .file_type()
                .is_symlink()
        );

        fs::remove_file(&zshrc).expect("remove test symlink");
        fs::write(&zshrc, "export SAFE=1\n").expect("zshrc");
        symlink("missing-init", &init).expect("init symlink");
        assert!(setup(&zshrc, &init, "ghis").is_err());
        assert_eq!(fs::read_to_string(&zshrc).unwrap(), "export SAFE=1\n");
        assert!(
            fs::symlink_metadata(&init)
                .unwrap()
                .file_type()
                .is_symlink()
        );
    }

    #[test]
    fn invalid_utf8_zshrc_rolls_back_the_init_file() {
        let directory = tempfile::tempdir().expect("tempdir");
        let zshrc = directory.path().join(".zshrc");
        let init = directory.path().join("init.zsh");
        fs::write(&zshrc, [b'#', 0xff, b'\n']).expect("invalid zshrc");
        fs::write(&init, "old init\n").expect("old init");

        let error = setup(&zshrc, &init, "ghis").expect_err("invalid UTF-8 must fail");
        assert_eq!(error.kind(), io::ErrorKind::InvalidData);
        assert_eq!(fs::read_to_string(&init).unwrap(), "old init\n");
        assert_eq!(fs::read(&zshrc).unwrap(), vec![b'#', 0xff, b'\n']);
        assert!(!directory.path().join(".zshrc.ghis.bak").exists());
    }

    #[cfg(unix)]
    #[test]
    fn setup_and_uninstall_preserve_existing_zshrc_mode() {
        use std::os::unix::fs::PermissionsExt;

        let directory = tempfile::tempdir().expect("tempdir");
        let zshrc = directory.path().join(".zshrc");
        let init = directory.path().join("init.zsh");
        fs::write(&zshrc, "export MODE=1\n").expect("zshrc");
        fs::set_permissions(&zshrc, fs::Permissions::from_mode(0o640)).expect("set mode");

        setup(&zshrc, &init, "ghis").expect("setup");
        assert_eq!(
            fs::metadata(&zshrc).unwrap().permissions().mode() & 0o777,
            0o640
        );
        uninstall(&zshrc).expect("uninstall");
        assert_eq!(
            fs::metadata(&zshrc).unwrap().permissions().mode() & 0o777,
            0o640
        );
    }
}
