//! zsh integration for `ghis`.
//!
//! The shell integration is deliberately small: the generated functions only
//! dispatch to the `ghis` executable and never evaluate user supplied input.
//! Paths are quoted as zsh single quoted strings and the managed block in
//! `.zshrc` can be installed and removed without touching any other content.

use std::ffi::OsStr;
use std::fs::{self, File, OpenOptions};
use std::io::{self, Read, Write};
use std::path::{Path, PathBuf};

#[cfg(unix)]
use std::os::unix::fs::{OpenOptionsExt, PermissionsExt};

/// Start marker for the block owned by ghis in a zsh startup file.
pub const START_MARKER: &str = "# >>> ghis setup >>>";
/// End marker for the block owned by ghis in a zsh startup file.
pub const END_MARKER: &str = "# <<< ghis setup <<<";
/// Exported by the generated init script so child `ghis` processes can tell
/// that this shell actually loaded the wrapper, rather than merely having a
/// setup block on disk.
pub const LOADED_ENV: &str = "GHIS_SHELL_INTEGRATION";

/// Resolve the zsh startup file using the same `ZDOTDIR` convention as zsh.
pub fn zshrc_path(home: &Path, zdotdir: Option<&OsStr>) -> PathBuf {
    zdotdir
        .filter(|value| !value.is_empty())
        .map(PathBuf::from)
        .unwrap_or_else(|| home.to_path_buf())
        .join(".zshrc")
}

/// Result of installing the shell integration.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SetupReport {
    /// Startup file that was updated.
    pub zshrc: PathBuf,
    /// Generated init file sourced by the startup file.
    pub init_file: PathBuf,
    /// Backup created before the first modification, if any.
    pub backup: Option<PathBuf>,
    /// Whether either file was changed.
    pub changed: bool,
}

/// Quote a value for use as a single zsh argument.
///
/// A single quoted shell word cannot interpolate variables, command
/// substitutions, backticks, globbing, or backslashes.  The only character
/// that needs escaping is a single quote, represented by closing the quote,
/// emitting `\'`, and opening it again.
pub fn shell_quote(value: &str) -> String {
    if value.is_empty() {
        return "''".to_string();
    }

    let mut quoted = String::with_capacity(value.len() + 2);
    quoted.push('\'');
    for character in value.chars() {
        if character == '\'' {
            quoted.push_str("'\\''");
        } else {
            quoted.push(character);
        }
    }
    quoted.push('\'');
    quoted
}

/// Return the generated zsh functions.
///
/// `binary` is usually `ghis`, but accepting a path makes development builds
/// and package managers work without changing the generated wrapper.  The
/// generated functions preserve stdin/stdout/stderr and the child exit code.
pub fn zsh_init_script(binary: &str) -> String {
    let binary = shell_quote(binary);
    format!(
        r#"# Generated by ghis. Do not edit this file; rerun `ghis setup`.
# The functions are intentionally wrappers, so aliases and all TTY streams
# remain owned by the caller. Set GHIS_BYPASS=1 for one command when needed.

typeset -gx GHIS_SHELL_INTEGRATION=1

_ghis_dispatch() {{
  local _ghis_kind="$1"
  shift
  if [[ "${{GHIS_BYPASS:-0}}" == 1 || "${{GHIS_WRAPPER_ACTIVE:-0}}" == 1 ]]; then
    command "$_ghis_kind" "$@"
    return $?
  fi
  if ! command -v {binary} >/dev/null 2>&1; then
    command "$_ghis_kind" "$@"
    return $?
  fi
  GHIS_WRAPPER_ACTIVE=1 command {binary} "$_ghis_kind" -- "$@"
}}

function git {{
  _ghis_dispatch git "$@"
}}

function gh {{
  _ghis_dispatch gh "$@"
}}

# Refreshing this local state is optional and never performs network access.
# A caller can set GHIS_DISABLE_CHPWD=1 when another chpwd hook owns this work.
autoload -Uz add-zsh-hook 2>/dev/null || true
_ghis_chpwd() {{
  [[ "${{GHIS_DISABLE_CHPWD:-0}}" == 1 ]] && return 0
  # Keep only a local hint; this must never perform network I/O or print.
  local _ghis_root
  _ghis_root="$(GHIS_BYPASS=1 command git rev-parse --show-toplevel 2>/dev/null)"
  typeset -g GHIS_REPO_ROOT="$_ghis_root"
}}
if (( $+functions[add-zsh-hook] )); then
  add-zsh-hook chpwd _ghis_chpwd
  _ghis_chpwd
fi
"#
    )
}

/// Compatibility name for callers that describe the generated functions as a
/// wrapper script.
pub fn zsh_wrapper_script(binary: &str) -> String {
    zsh_init_script(binary)
}

/// Compatibility name used by setup/diagnostic commands.
pub fn generate_init(binary: &str) -> String {
    zsh_init_script(binary)
}

/// Whether the current process was started from a shell that sourced the
/// generated init script. This marker is diagnostic only and grants no trust
/// or authorization by itself.
pub fn integration_is_loaded() -> bool {
    std::env::var_os(LOADED_ENV).as_deref() == Some(OsStr::new("1"))
}

/// Check that both generated files still contain exactly the setup ghis would
/// install now. This is read-only and does not imply the current shell sourced
/// either file.
pub fn integration_is_installed(zshrc: &Path, init_file: &Path, binary: &str) -> bool {
    let expected_init = zsh_init_script(binary);
    let expected_block = managed_block(init_file);
    fs::read_to_string(init_file).ok().as_deref() == Some(expected_init.as_str())
        && fs::read_to_string(zshrc)
            .ok()
            .is_some_and(|contents| contents.contains(expected_block.trim_end()))
}

/// Generate zsh glue for the wrapped commands.
///
/// `git` and `gh` already have mature completion functions.  The wrapper
/// should preserve those functions instead of trying to feed their words into
/// ghis's own static completion generator.
pub fn zsh_completion_script(_binary: &str) -> String {
    r#"#compdef git gh

if (( $+functions[_git] )); then
  compdef _git git
fi
if (( $+functions[_gh] )); then
  compdef _gh gh
fi
"#
    .to_string()
}

/// Render the small source block inserted into `.zshrc`.
pub fn managed_block(init_file: &Path) -> String {
    format!(
        "{START_MARKER}\nif [[ -r {path} ]]; then\n  source {path}\nfi\n{END_MARKER}",
        path = shell_quote(&init_file.to_string_lossy())
    )
}

/// Remove every complete managed block from `contents`.
///
/// The function leaves malformed/incomplete blocks untouched.  This is
/// intentional: silently deleting a user file after a truncated write is more
/// surprising than asking the user to repair the marker manually.
pub fn remove_managed_blocks(contents: &str) -> (String, bool) {
    let mut output = String::with_capacity(contents.len());
    let mut cursor = 0usize;
    let mut changed = false;

    while let Some(start_rel) = contents[cursor..].find(START_MARKER) {
        let start = cursor + start_rel;
        let Some(end_rel) = contents[start + START_MARKER.len()..].find(END_MARKER) else {
            break;
        };
        let end_marker = start + START_MARKER.len() + end_rel;
        let mut end = end_marker + END_MARKER.len();
        // Consume one line ending, while preserving the surrounding content.
        if contents[end..].starts_with("\r\n") {
            end += 2;
        } else if contents[end..].starts_with('\n') || contents[end..].starts_with('\r') {
            end += 1;
        }
        // `replace_managed_block` owns one separator line before the marker.
        // Remove that separator as part of uninstall so the pre-setup content
        // is restored byte-for-byte in the normal case.
        let owned_start = if contents[cursor..start].ends_with("\r\n\r\n") {
            start - 2
        } else if contents[cursor..start].ends_with("\n\n")
            || contents[cursor..start].ends_with("\r\r")
        {
            start - 1
        } else {
            start
        };
        output.push_str(&contents[cursor..owned_start]);
        cursor = end;
        changed = true;
    }

    output.push_str(&contents[cursor..]);
    (output, changed)
}

/// Replace ghis's block in a startup file, preserving unrelated text.
pub fn replace_managed_block(contents: &str, block: &str) -> String {
    let (mut cleaned, _) = remove_managed_blocks(contents);
    if !cleaned.is_empty() && !cleaned.ends_with('\n') {
        cleaned.push('\n');
    }
    if !cleaned.is_empty() {
        // Separate the generated block from a previous line without creating
        // duplicate blank lines on repeated setup calls.
        if !cleaned.ends_with("\n\n") {
            cleaned.push('\n');
        }
    }
    cleaned.push_str(block.trim_end_matches(['\n', '\r']));
    cleaned.push('\n');
    cleaned
}

/// Install the generated init file and managed `.zshrc` source block.
pub fn setup(
    zshrc: impl AsRef<Path>,
    init_file: impl AsRef<Path>,
    binary: &str,
) -> io::Result<SetupReport> {
    let zshrc = zshrc.as_ref().to_path_buf();
    let zshrc_target = editable_target(&zshrc)?;
    let init_file = init_file.as_ref().to_path_buf();
    let init_target = editable_target(&init_file)?;

    if let Some(parent) = init_target.parent() {
        fs::create_dir_all(parent)?;
    }
    let init_content = zsh_init_script(binary);
    let init_changed = read_optional(&init_target)?.as_deref() != Some(init_content.as_str());
    if init_changed {
        atomic_write(
            &init_target,
            init_content.as_bytes(),
            metadata_mode(&init_target),
        )?;
    }

    if let Some(parent) = zshrc_target.parent() {
        fs::create_dir_all(parent)?;
    }
    let existing = read_optional(&zshrc_target)?.unwrap_or_default();
    let block = managed_block(&init_file);
    let updated = replace_managed_block(&existing, &block);
    let zshrc_changed = updated != existing;
    let mut backup = None;
    if zshrc_changed {
        let backup_path = PathBuf::from(format!("{}.ghis.bak", zshrc.display()));
        if !backup_path.exists() {
            // A backup is made only once so repeated setup cannot overwrite
            // the user's original file with a later generated version.
            if zshrc_target.exists() {
                fs::copy(&zshrc_target, &backup_path)?;
                backup = Some(backup_path);
            }
        }
        let mode = metadata_mode(&zshrc_target);
        atomic_write(&zshrc_target, updated.as_bytes(), mode)?;
    }

    Ok(SetupReport {
        zshrc,
        init_file,
        backup,
        changed: init_changed || zshrc_changed,
    })
}

/// Remove ghis's managed block from a startup file.
///
/// The generated init file and backup are intentionally retained.  They are
/// useful for recovery and deleting them would make uninstall less reversible.
pub fn uninstall(zshrc: impl AsRef<Path>) -> io::Result<bool> {
    let zshrc = zshrc.as_ref();
    let target = editable_target(zshrc)?;
    let Some(existing) = read_optional(&target)? else {
        return Ok(false);
    };
    let (updated, changed) = remove_managed_blocks(&existing);
    if changed {
        let mode = metadata_mode(&target);
        atomic_write(&target, updated.as_bytes(), mode)?;
    }
    Ok(changed)
}

/// Explicitly named aliases for callers that prefer operation-oriented names.
pub fn setup_zsh(
    zshrc: impl AsRef<Path>,
    init_file: impl AsRef<Path>,
    binary: &str,
) -> io::Result<SetupReport> {
    setup(zshrc, init_file, binary)
}

/// Remove the managed zsh block (the generated file is retained).
pub fn uninstall_zsh(zshrc: impl AsRef<Path>) -> io::Result<bool> {
    uninstall(zshrc)
}

fn read_optional(path: &Path) -> io::Result<Option<String>> {
    if !path.exists() {
        return Ok(None);
    }
    let mut content = String::new();
    File::open(path)?.read_to_string(&mut content)?;
    Ok(Some(content))
}

fn editable_target(path: &Path) -> io::Result<PathBuf> {
    match fs::symlink_metadata(path) {
        Ok(metadata) if metadata.file_type().is_symlink() => {
            let target = fs::read_link(path)?;
            let target = if target.is_absolute() {
                target
            } else {
                path.parent().unwrap_or_else(|| Path::new(".")).join(target)
            };
            // Resolve a possible link chain and reject dangling links instead
            // of replacing the user's symlink with a generated regular file.
            fs::canonicalize(target)
        }
        Ok(_) => Ok(path.to_path_buf()),
        Err(error) if error.kind() == io::ErrorKind::NotFound => Ok(path.to_path_buf()),
        Err(error) => Err(error),
    }
}

fn metadata_mode(path: &Path) -> Option<u32> {
    #[cfg(unix)]
    {
        path.metadata()
            .ok()
            .map(|metadata| metadata.permissions().mode())
    }
    #[cfg(not(unix))]
    {
        let _ = path;
        None
    }
}

fn atomic_write(path: &Path, contents: &[u8], mode: Option<u32>) -> io::Result<()> {
    let parent = path.parent().unwrap_or_else(|| Path::new("."));
    let name = path
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("ghis-file");
    let temporary = parent.join(format!(".{name}.ghis-tmp-{}", std::process::id()));

    let result = (|| {
        let mut options = OpenOptions::new();
        options.write(true).create(true).truncate(true);
        #[cfg(unix)]
        {
            options.mode(mode.unwrap_or(0o600));
        }
        let mut file = options.open(&temporary)?;
        file.write_all(contents)?;
        file.sync_all()?;
        #[cfg(unix)]
        if let Some(mode) = mode {
            fs::set_permissions(&temporary, fs::Permissions::from_mode(mode))?;
        }
        fs::rename(&temporary, path)
    })();

    if result.is_err() {
        let _ = fs::remove_file(&temporary);
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    #[test]
    fn quote_handles_shell_metacharacters() {
        assert_eq!(shell_quote(""), "''");
        assert_eq!(shell_quote("a'b $HOME\n🙂"), "'a'\\''b $HOME\n🙂'");
    }

    #[test]
    fn zshrc_path_prefers_non_empty_zdotdir() {
        assert_eq!(
            zshrc_path(Path::new("/home/alice"), Some(OsStr::new("/tmp/zsh"))),
            PathBuf::from("/tmp/zsh/.zshrc")
        );
        assert_eq!(
            zshrc_path(Path::new("/home/alice"), Some(OsStr::new(""))),
            PathBuf::from("/home/alice/.zshrc")
        );
        assert_eq!(
            zshrc_path(Path::new("/home/alice"), None),
            PathBuf::from("/home/alice/.zshrc")
        );
    }

    #[test]
    fn replacement_is_idempotent() {
        let block = managed_block(Path::new("/tmp/a path/init.zsh"));
        let once = replace_managed_block("export A=1\n", &block);
        let twice = replace_managed_block(&once, &block);
        assert_eq!(once, twice);
        assert_eq!(once.matches(START_MARKER).count(), 1);
    }

    #[test]
    fn malformed_block_is_not_removed() {
        let input = format!("before\n{START_MARKER}\ntruncated\n");
        let (output, changed) = remove_managed_blocks(&input);
        assert!(!changed);
        assert_eq!(output, input);
    }

    #[test]
    fn setup_and_uninstall_round_trip() {
        let directory = tempfile::tempdir().expect("tempdir");
        let zshrc = directory.path().join(".zshrc");
        let init = directory.path().join("config/init.zsh");
        fs::write(&zshrc, "export TEST=1\n").expect("write");
        let report = setup(&zshrc, &init, "ghis").expect("setup");
        assert!(report.changed);
        assert!(report.backup.is_some());
        assert!(integration_is_installed(&zshrc, &init, "ghis"));
        assert!(
            fs::read_to_string(&zshrc)
                .expect("read")
                .contains(START_MARKER)
        );
        let second = setup(&zshrc, &init, "ghis").expect("second setup");
        assert!(!second.changed);
        assert!(uninstall(&zshrc).expect("uninstall"));
        let after_uninstall = fs::read_to_string(&zshrc).expect("read");
        assert!(!after_uninstall.contains(START_MARKER));
        assert!(!integration_is_installed(&zshrc, &init, "ghis"));
        assert_eq!(after_uninstall, "export TEST=1\n");
        assert!(!uninstall(&zshrc).expect("second uninstall"));
        assert_eq!(fs::read_to_string(&zshrc).expect("read"), after_uninstall);
    }

    #[cfg(unix)]
    #[test]
    fn setup_and_uninstall_preserve_a_zshrc_symlink() {
        use std::os::unix::fs::symlink;

        let directory = tempfile::tempdir().expect("tempdir");
        let target = directory.path().join("dotfiles/zshrc");
        fs::create_dir_all(target.parent().unwrap()).expect("target directory");
        fs::write(&target, "export LINKED=1\n").expect("target");
        let zshrc = directory.path().join(".zshrc");
        symlink("dotfiles/zshrc", &zshrc).expect("symlink");
        let init = directory.path().join("config/init.zsh");

        setup(&zshrc, &init, "ghis").expect("setup through symlink");
        assert!(
            fs::symlink_metadata(&zshrc)
                .unwrap()
                .file_type()
                .is_symlink()
        );
        assert!(fs::read_to_string(&target).unwrap().contains(START_MARKER));

        assert!(uninstall(&zshrc).expect("uninstall through symlink"));
        assert!(
            fs::symlink_metadata(&zshrc)
                .unwrap()
                .file_type()
                .is_symlink()
        );
        assert_eq!(fs::read_to_string(&target).unwrap(), "export LINKED=1\n");
    }
}
